/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedOOrgRouteRouteImport } from './routes/_authenticated/o/$org/route'
import { Route as AuthenticatedOOrgIndexRouteImport } from './routes/_authenticated/o/$org/index'
import { Route as AuthenticatedOOrgDashboardsIndexRouteImport } from './routes/_authenticated/o/$org/dashboards/index'
import { Route as AuthenticatedOOrgSettingsOrgsRouteImport } from './routes/_authenticated/o/$org/settings/orgs'
import { Route as AuthenticatedOOrgSSiteSlugRouteRouteImport } from './routes/_authenticated/o/$org/s/$siteSlug/route'
import { Route as AuthenticatedOOrgDashboardsDashSlugIndexRouteImport } from './routes/_authenticated/o/$org/dashboards/$dashSlug/index'
import { Route as AuthenticatedOOrgDashboardsDashSlugEditRouteImport } from './routes/_authenticated/o/$org/dashboards/$dashSlug/edit'
import { Route as AuthenticatedOOrgSSiteSlugSparksIndexRouteImport } from './routes/_authenticated/o/$org/s/$siteSlug/sparks/index'
import { Route as AuthenticatedOOrgSSiteSlugRunsIndexRouteImport } from './routes/_authenticated/o/$org/s/$siteSlug/runs/index'
import { Route as AuthenticatedOOrgSSiteSlugRulesIndexRouteImport } from './routes/_authenticated/o/$org/s/$siteSlug/rules/index'
import { Route as AuthenticatedOOrgSSiteSlugPointsIndexRouteImport } from './routes/_authenticated/o/$org/s/$siteSlug/points/index'
import { Route as AuthenticatedOOrgSSiteSlugHistoryIndexRouteImport } from './routes/_authenticated/o/$org/s/$siteSlug/history/index'
import { Route as AuthenticatedOOrgSSiteSlugFlowsIndexRouteImport } from './routes/_authenticated/o/$org/s/$siteSlug/flows/index'
import { Route as AuthenticatedOOrgSSiteSlugRunsRunIdRouteImport } from './routes/_authenticated/o/$org/s/$siteSlug/runs/$runId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOOrgRouteRoute = AuthenticatedOOrgRouteRouteImport.update({
  id: '/o/$org',
  path: '/o/$org',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOOrgIndexRoute = AuthenticatedOOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOOrgRouteRoute,
} as any)
const AuthenticatedOOrgDashboardsIndexRoute =
  AuthenticatedOOrgDashboardsIndexRouteImport.update({
    id: '/dashboards/',
    path: '/dashboards/',
    getParentRoute: () => AuthenticatedOOrgRouteRoute,
  } as any)
const AuthenticatedOOrgSettingsOrgsRoute =
  AuthenticatedOOrgSettingsOrgsRouteImport.update({
    id: '/settings/orgs',
    path: '/settings/orgs',
    getParentRoute: () => AuthenticatedOOrgRouteRoute,
  } as any)
const AuthenticatedOOrgSSiteSlugRouteRoute =
  AuthenticatedOOrgSSiteSlugRouteRouteImport.update({
    id: '/s/$siteSlug',
    path: '/s/$siteSlug',
    getParentRoute: () => AuthenticatedOOrgRouteRoute,
  } as any)
const AuthenticatedOOrgDashboardsDashSlugIndexRoute =
  AuthenticatedOOrgDashboardsDashSlugIndexRouteImport.update({
    id: '/dashboards/$dashSlug/',
    path: '/dashboards/$dashSlug/',
    getParentRoute: () => AuthenticatedOOrgRouteRoute,
  } as any)
const AuthenticatedOOrgDashboardsDashSlugEditRoute =
  AuthenticatedOOrgDashboardsDashSlugEditRouteImport.update({
    id: '/dashboards/$dashSlug/edit',
    path: '/dashboards/$dashSlug/edit',
    getParentRoute: () => AuthenticatedOOrgRouteRoute,
  } as any)
const AuthenticatedOOrgSSiteSlugSparksIndexRoute =
  AuthenticatedOOrgSSiteSlugSparksIndexRouteImport.update({
    id: '/sparks/',
    path: '/sparks/',
    getParentRoute: () => AuthenticatedOOrgSSiteSlugRouteRoute,
  } as any)
const AuthenticatedOOrgSSiteSlugRunsIndexRoute =
  AuthenticatedOOrgSSiteSlugRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => AuthenticatedOOrgSSiteSlugRouteRoute,
  } as any)
const AuthenticatedOOrgSSiteSlugRulesIndexRoute =
  AuthenticatedOOrgSSiteSlugRulesIndexRouteImport.update({
    id: '/rules/',
    path: '/rules/',
    getParentRoute: () => AuthenticatedOOrgSSiteSlugRouteRoute,
  } as any)
const AuthenticatedOOrgSSiteSlugPointsIndexRoute =
  AuthenticatedOOrgSSiteSlugPointsIndexRouteImport.update({
    id: '/points/',
    path: '/points/',
    getParentRoute: () => AuthenticatedOOrgSSiteSlugRouteRoute,
  } as any)
const AuthenticatedOOrgSSiteSlugHistoryIndexRoute =
  AuthenticatedOOrgSSiteSlugHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedOOrgSSiteSlugRouteRoute,
  } as any)
const AuthenticatedOOrgSSiteSlugFlowsIndexRoute =
  AuthenticatedOOrgSSiteSlugFlowsIndexRouteImport.update({
    id: '/flows/',
    path: '/flows/',
    getParentRoute: () => AuthenticatedOOrgSSiteSlugRouteRoute,
  } as any)
const AuthenticatedOOrgSSiteSlugRunsRunIdRoute =
  AuthenticatedOOrgSSiteSlugRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => AuthenticatedOOrgSSiteSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/o/$org': typeof AuthenticatedOOrgRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/o/$org/': typeof AuthenticatedOOrgIndexRoute
  '/o/$org/s/$siteSlug': typeof AuthenticatedOOrgSSiteSlugRouteRouteWithChildren
  '/o/$org/settings/orgs': typeof AuthenticatedOOrgSettingsOrgsRoute
  '/o/$org/dashboards/': typeof AuthenticatedOOrgDashboardsIndexRoute
  '/o/$org/dashboards/$dashSlug/edit': typeof AuthenticatedOOrgDashboardsDashSlugEditRoute
  '/o/$org/dashboards/$dashSlug/': typeof AuthenticatedOOrgDashboardsDashSlugIndexRoute
  '/o/$org/s/$siteSlug/runs/$runId': typeof AuthenticatedOOrgSSiteSlugRunsRunIdRoute
  '/o/$org/s/$siteSlug/flows/': typeof AuthenticatedOOrgSSiteSlugFlowsIndexRoute
  '/o/$org/s/$siteSlug/history/': typeof AuthenticatedOOrgSSiteSlugHistoryIndexRoute
  '/o/$org/s/$siteSlug/points/': typeof AuthenticatedOOrgSSiteSlugPointsIndexRoute
  '/o/$org/s/$siteSlug/rules/': typeof AuthenticatedOOrgSSiteSlugRulesIndexRoute
  '/o/$org/s/$siteSlug/runs/': typeof AuthenticatedOOrgSSiteSlugRunsIndexRoute
  '/o/$org/s/$siteSlug/sparks/': typeof AuthenticatedOOrgSSiteSlugSparksIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/o/$org': typeof AuthenticatedOOrgIndexRoute
  '/o/$org/s/$siteSlug': typeof AuthenticatedOOrgSSiteSlugRouteRouteWithChildren
  '/o/$org/settings/orgs': typeof AuthenticatedOOrgSettingsOrgsRoute
  '/o/$org/dashboards': typeof AuthenticatedOOrgDashboardsIndexRoute
  '/o/$org/dashboards/$dashSlug/edit': typeof AuthenticatedOOrgDashboardsDashSlugEditRoute
  '/o/$org/dashboards/$dashSlug': typeof AuthenticatedOOrgDashboardsDashSlugIndexRoute
  '/o/$org/s/$siteSlug/runs/$runId': typeof AuthenticatedOOrgSSiteSlugRunsRunIdRoute
  '/o/$org/s/$siteSlug/flows': typeof AuthenticatedOOrgSSiteSlugFlowsIndexRoute
  '/o/$org/s/$siteSlug/history': typeof AuthenticatedOOrgSSiteSlugHistoryIndexRoute
  '/o/$org/s/$siteSlug/points': typeof AuthenticatedOOrgSSiteSlugPointsIndexRoute
  '/o/$org/s/$siteSlug/rules': typeof AuthenticatedOOrgSSiteSlugRulesIndexRoute
  '/o/$org/s/$siteSlug/runs': typeof AuthenticatedOOrgSSiteSlugRunsIndexRoute
  '/o/$org/s/$siteSlug/sparks': typeof AuthenticatedOOrgSSiteSlugSparksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/o/$org': typeof AuthenticatedOOrgRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/o/$org/': typeof AuthenticatedOOrgIndexRoute
  '/_authenticated/o/$org/s/$siteSlug': typeof AuthenticatedOOrgSSiteSlugRouteRouteWithChildren
  '/_authenticated/o/$org/settings/orgs': typeof AuthenticatedOOrgSettingsOrgsRoute
  '/_authenticated/o/$org/dashboards/': typeof AuthenticatedOOrgDashboardsIndexRoute
  '/_authenticated/o/$org/dashboards/$dashSlug/edit': typeof AuthenticatedOOrgDashboardsDashSlugEditRoute
  '/_authenticated/o/$org/dashboards/$dashSlug/': typeof AuthenticatedOOrgDashboardsDashSlugIndexRoute
  '/_authenticated/o/$org/s/$siteSlug/runs/$runId': typeof AuthenticatedOOrgSSiteSlugRunsRunIdRoute
  '/_authenticated/o/$org/s/$siteSlug/flows/': typeof AuthenticatedOOrgSSiteSlugFlowsIndexRoute
  '/_authenticated/o/$org/s/$siteSlug/history/': typeof AuthenticatedOOrgSSiteSlugHistoryIndexRoute
  '/_authenticated/o/$org/s/$siteSlug/points/': typeof AuthenticatedOOrgSSiteSlugPointsIndexRoute
  '/_authenticated/o/$org/s/$siteSlug/rules/': typeof AuthenticatedOOrgSSiteSlugRulesIndexRoute
  '/_authenticated/o/$org/s/$siteSlug/runs/': typeof AuthenticatedOOrgSSiteSlugRunsIndexRoute
  '/_authenticated/o/$org/s/$siteSlug/sparks/': typeof AuthenticatedOOrgSSiteSlugSparksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/o/$org'
    | '/errors/$error'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/'
    | '/o/$org/'
    | '/o/$org/s/$siteSlug'
    | '/o/$org/settings/orgs'
    | '/o/$org/dashboards/'
    | '/o/$org/dashboards/$dashSlug/edit'
    | '/o/$org/dashboards/$dashSlug/'
    | '/o/$org/s/$siteSlug/runs/$runId'
    | '/o/$org/s/$siteSlug/flows/'
    | '/o/$org/s/$siteSlug/history/'
    | '/o/$org/s/$siteSlug/points/'
    | '/o/$org/s/$siteSlug/rules/'
    | '/o/$org/s/$siteSlug/runs/'
    | '/o/$org/s/$siteSlug/sparks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings'
    | '/o/$org'
    | '/o/$org/s/$siteSlug'
    | '/o/$org/settings/orgs'
    | '/o/$org/dashboards'
    | '/o/$org/dashboards/$dashSlug/edit'
    | '/o/$org/dashboards/$dashSlug'
    | '/o/$org/s/$siteSlug/runs/$runId'
    | '/o/$org/s/$siteSlug/flows'
    | '/o/$org/s/$siteSlug/history'
    | '/o/$org/s/$siteSlug/points'
    | '/o/$org/s/$siteSlug/rules'
    | '/o/$org/s/$siteSlug/runs'
    | '/o/$org/s/$siteSlug/sparks'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/o/$org'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/'
    | '/_authenticated/o/$org/'
    | '/_authenticated/o/$org/s/$siteSlug'
    | '/_authenticated/o/$org/settings/orgs'
    | '/_authenticated/o/$org/dashboards/'
    | '/_authenticated/o/$org/dashboards/$dashSlug/edit'
    | '/_authenticated/o/$org/dashboards/$dashSlug/'
    | '/_authenticated/o/$org/s/$siteSlug/runs/$runId'
    | '/_authenticated/o/$org/s/$siteSlug/flows/'
    | '/_authenticated/o/$org/s/$siteSlug/history/'
    | '/_authenticated/o/$org/s/$siteSlug/points/'
    | '/_authenticated/o/$org/s/$siteSlug/rules/'
    | '/_authenticated/o/$org/s/$siteSlug/runs/'
    | '/_authenticated/o/$org/s/$siteSlug/sparks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/o/$org': {
      id: '/_authenticated/o/$org'
      path: '/o/$org'
      fullPath: '/o/$org'
      preLoaderRoute: typeof AuthenticatedOOrgRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/o/$org/': {
      id: '/_authenticated/o/$org/'
      path: '/'
      fullPath: '/o/$org/'
      preLoaderRoute: typeof AuthenticatedOOrgIndexRouteImport
      parentRoute: typeof AuthenticatedOOrgRouteRoute
    }
    '/_authenticated/o/$org/dashboards/': {
      id: '/_authenticated/o/$org/dashboards/'
      path: '/dashboards'
      fullPath: '/o/$org/dashboards/'
      preLoaderRoute: typeof AuthenticatedOOrgDashboardsIndexRouteImport
      parentRoute: typeof AuthenticatedOOrgRouteRoute
    }
    '/_authenticated/o/$org/settings/orgs': {
      id: '/_authenticated/o/$org/settings/orgs'
      path: '/settings/orgs'
      fullPath: '/o/$org/settings/orgs'
      preLoaderRoute: typeof AuthenticatedOOrgSettingsOrgsRouteImport
      parentRoute: typeof AuthenticatedOOrgRouteRoute
    }
    '/_authenticated/o/$org/s/$siteSlug': {
      id: '/_authenticated/o/$org/s/$siteSlug'
      path: '/s/$siteSlug'
      fullPath: '/o/$org/s/$siteSlug'
      preLoaderRoute: typeof AuthenticatedOOrgSSiteSlugRouteRouteImport
      parentRoute: typeof AuthenticatedOOrgRouteRoute
    }
    '/_authenticated/o/$org/dashboards/$dashSlug/': {
      id: '/_authenticated/o/$org/dashboards/$dashSlug/'
      path: '/dashboards/$dashSlug'
      fullPath: '/o/$org/dashboards/$dashSlug/'
      preLoaderRoute: typeof AuthenticatedOOrgDashboardsDashSlugIndexRouteImport
      parentRoute: typeof AuthenticatedOOrgRouteRoute
    }
    '/_authenticated/o/$org/dashboards/$dashSlug/edit': {
      id: '/_authenticated/o/$org/dashboards/$dashSlug/edit'
      path: '/dashboards/$dashSlug/edit'
      fullPath: '/o/$org/dashboards/$dashSlug/edit'
      preLoaderRoute: typeof AuthenticatedOOrgDashboardsDashSlugEditRouteImport
      parentRoute: typeof AuthenticatedOOrgRouteRoute
    }
    '/_authenticated/o/$org/s/$siteSlug/sparks/': {
      id: '/_authenticated/o/$org/s/$siteSlug/sparks/'
      path: '/sparks'
      fullPath: '/o/$org/s/$siteSlug/sparks/'
      preLoaderRoute: typeof AuthenticatedOOrgSSiteSlugSparksIndexRouteImport
      parentRoute: typeof AuthenticatedOOrgSSiteSlugRouteRoute
    }
    '/_authenticated/o/$org/s/$siteSlug/runs/': {
      id: '/_authenticated/o/$org/s/$siteSlug/runs/'
      path: '/runs'
      fullPath: '/o/$org/s/$siteSlug/runs/'
      preLoaderRoute: typeof AuthenticatedOOrgSSiteSlugRunsIndexRouteImport
      parentRoute: typeof AuthenticatedOOrgSSiteSlugRouteRoute
    }
    '/_authenticated/o/$org/s/$siteSlug/rules/': {
      id: '/_authenticated/o/$org/s/$siteSlug/rules/'
      path: '/rules'
      fullPath: '/o/$org/s/$siteSlug/rules/'
      preLoaderRoute: typeof AuthenticatedOOrgSSiteSlugRulesIndexRouteImport
      parentRoute: typeof AuthenticatedOOrgSSiteSlugRouteRoute
    }
    '/_authenticated/o/$org/s/$siteSlug/points/': {
      id: '/_authenticated/o/$org/s/$siteSlug/points/'
      path: '/points'
      fullPath: '/o/$org/s/$siteSlug/points/'
      preLoaderRoute: typeof AuthenticatedOOrgSSiteSlugPointsIndexRouteImport
      parentRoute: typeof AuthenticatedOOrgSSiteSlugRouteRoute
    }
    '/_authenticated/o/$org/s/$siteSlug/history/': {
      id: '/_authenticated/o/$org/s/$siteSlug/history/'
      path: '/history'
      fullPath: '/o/$org/s/$siteSlug/history/'
      preLoaderRoute: typeof AuthenticatedOOrgSSiteSlugHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedOOrgSSiteSlugRouteRoute
    }
    '/_authenticated/o/$org/s/$siteSlug/flows/': {
      id: '/_authenticated/o/$org/s/$siteSlug/flows/'
      path: '/flows'
      fullPath: '/o/$org/s/$siteSlug/flows/'
      preLoaderRoute: typeof AuthenticatedOOrgSSiteSlugFlowsIndexRouteImport
      parentRoute: typeof AuthenticatedOOrgSSiteSlugRouteRoute
    }
    '/_authenticated/o/$org/s/$siteSlug/runs/$runId': {
      id: '/_authenticated/o/$org/s/$siteSlug/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/o/$org/s/$siteSlug/runs/$runId'
      preLoaderRoute: typeof AuthenticatedOOrgSSiteSlugRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedOOrgSSiteSlugRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedOOrgSSiteSlugRouteRouteChildren {
  AuthenticatedOOrgSSiteSlugRunsRunIdRoute: typeof AuthenticatedOOrgSSiteSlugRunsRunIdRoute
  AuthenticatedOOrgSSiteSlugFlowsIndexRoute: typeof AuthenticatedOOrgSSiteSlugFlowsIndexRoute
  AuthenticatedOOrgSSiteSlugHistoryIndexRoute: typeof AuthenticatedOOrgSSiteSlugHistoryIndexRoute
  AuthenticatedOOrgSSiteSlugPointsIndexRoute: typeof AuthenticatedOOrgSSiteSlugPointsIndexRoute
  AuthenticatedOOrgSSiteSlugRulesIndexRoute: typeof AuthenticatedOOrgSSiteSlugRulesIndexRoute
  AuthenticatedOOrgSSiteSlugRunsIndexRoute: typeof AuthenticatedOOrgSSiteSlugRunsIndexRoute
  AuthenticatedOOrgSSiteSlugSparksIndexRoute: typeof AuthenticatedOOrgSSiteSlugSparksIndexRoute
}

const AuthenticatedOOrgSSiteSlugRouteRouteChildren: AuthenticatedOOrgSSiteSlugRouteRouteChildren =
  {
    AuthenticatedOOrgSSiteSlugRunsRunIdRoute:
      AuthenticatedOOrgSSiteSlugRunsRunIdRoute,
    AuthenticatedOOrgSSiteSlugFlowsIndexRoute:
      AuthenticatedOOrgSSiteSlugFlowsIndexRoute,
    AuthenticatedOOrgSSiteSlugHistoryIndexRoute:
      AuthenticatedOOrgSSiteSlugHistoryIndexRoute,
    AuthenticatedOOrgSSiteSlugPointsIndexRoute:
      AuthenticatedOOrgSSiteSlugPointsIndexRoute,
    AuthenticatedOOrgSSiteSlugRulesIndexRoute:
      AuthenticatedOOrgSSiteSlugRulesIndexRoute,
    AuthenticatedOOrgSSiteSlugRunsIndexRoute:
      AuthenticatedOOrgSSiteSlugRunsIndexRoute,
    AuthenticatedOOrgSSiteSlugSparksIndexRoute:
      AuthenticatedOOrgSSiteSlugSparksIndexRoute,
  }

const AuthenticatedOOrgSSiteSlugRouteRouteWithChildren =
  AuthenticatedOOrgSSiteSlugRouteRoute._addFileChildren(
    AuthenticatedOOrgSSiteSlugRouteRouteChildren,
  )

interface AuthenticatedOOrgRouteRouteChildren {
  AuthenticatedOOrgIndexRoute: typeof AuthenticatedOOrgIndexRoute
  AuthenticatedOOrgSSiteSlugRouteRoute: typeof AuthenticatedOOrgSSiteSlugRouteRouteWithChildren
  AuthenticatedOOrgSettingsOrgsRoute: typeof AuthenticatedOOrgSettingsOrgsRoute
  AuthenticatedOOrgDashboardsIndexRoute: typeof AuthenticatedOOrgDashboardsIndexRoute
  AuthenticatedOOrgDashboardsDashSlugEditRoute: typeof AuthenticatedOOrgDashboardsDashSlugEditRoute
  AuthenticatedOOrgDashboardsDashSlugIndexRoute: typeof AuthenticatedOOrgDashboardsDashSlugIndexRoute
}

const AuthenticatedOOrgRouteRouteChildren: AuthenticatedOOrgRouteRouteChildren =
  {
    AuthenticatedOOrgIndexRoute: AuthenticatedOOrgIndexRoute,
    AuthenticatedOOrgSSiteSlugRouteRoute:
      AuthenticatedOOrgSSiteSlugRouteRouteWithChildren,
    AuthenticatedOOrgSettingsOrgsRoute: AuthenticatedOOrgSettingsOrgsRoute,
    AuthenticatedOOrgDashboardsIndexRoute:
      AuthenticatedOOrgDashboardsIndexRoute,
    AuthenticatedOOrgDashboardsDashSlugEditRoute:
      AuthenticatedOOrgDashboardsDashSlugEditRoute,
    AuthenticatedOOrgDashboardsDashSlugIndexRoute:
      AuthenticatedOOrgDashboardsDashSlugIndexRoute,
  }

const AuthenticatedOOrgRouteRouteWithChildren =
  AuthenticatedOOrgRouteRoute._addFileChildren(
    AuthenticatedOOrgRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOOrgRouteRoute: typeof AuthenticatedOOrgRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOOrgRouteRoute: AuthenticatedOOrgRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
