/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWizardsRouteImport } from './routes/_authenticated/wizards'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedDashboardsRouteImport } from './routes/_authenticated/dashboards'
import { Route as AuthenticatedAlarmsRouteImport } from './routes/_authenticated/alarms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin/tenants'
import { Route as AuthenticatedAdminSitesRouteImport } from './routes/_authenticated/admin/sites'
import { Route as AuthenticatedAdminMetersRouteImport } from './routes/_authenticated/admin/meters'
import { Route as AuthenticatedAdminMeterTypesRouteImport } from './routes/_authenticated/admin/meter-types'
import { Route as AuthenticatedAdminGatewaysRouteImport } from './routes/_authenticated/admin/gateways'
import { Route as AuthenticatedAdminDataConsoleRouteImport } from './routes/_authenticated/admin/data-console'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWizardsRoute = AuthenticatedWizardsRouteImport.update({
  id: '/wizards',
  path: '/wizards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardsRoute = AuthenticatedDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlarmsRoute = AuthenticatedAlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSitesRoute = AuthenticatedAdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMetersRoute =
  AuthenticatedAdminMetersRouteImport.update({
    id: '/meters',
    path: '/meters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMeterTypesRoute =
  AuthenticatedAdminMeterTypesRouteImport.update({
    id: '/meter-types',
    path: '/meter-types',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGatewaysRoute =
  AuthenticatedAdminGatewaysRouteImport.update({
    id: '/gateways',
    path: '/gateways',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDataConsoleRoute =
  AuthenticatedAdminDataConsoleRouteImport.update({
    id: '/data-console',
    path: '/data-console',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/alarms': typeof AuthenticatedAlarmsRoute
  '/dashboards': typeof AuthenticatedDashboardsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/wizards': typeof AuthenticatedWizardsRoute
  '/admin/data-console': typeof AuthenticatedAdminDataConsoleRoute
  '/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/admin/meter-types': typeof AuthenticatedAdminMeterTypesRoute
  '/admin/meters': typeof AuthenticatedAdminMetersRoute
  '/admin/sites': typeof AuthenticatedAdminSitesRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/alarms': typeof AuthenticatedAlarmsRoute
  '/dashboards': typeof AuthenticatedDashboardsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/wizards': typeof AuthenticatedWizardsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/data-console': typeof AuthenticatedAdminDataConsoleRoute
  '/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/admin/meter-types': typeof AuthenticatedAdminMeterTypesRoute
  '/admin/meters': typeof AuthenticatedAdminMetersRoute
  '/admin/sites': typeof AuthenticatedAdminSitesRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/alarms': typeof AuthenticatedAlarmsRoute
  '/_authenticated/dashboards': typeof AuthenticatedDashboardsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/wizards': typeof AuthenticatedWizardsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/data-console': typeof AuthenticatedAdminDataConsoleRoute
  '/_authenticated/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/_authenticated/admin/meter-types': typeof AuthenticatedAdminMeterTypesRoute
  '/_authenticated/admin/meters': typeof AuthenticatedAdminMetersRoute
  '/_authenticated/admin/sites': typeof AuthenticatedAdminSitesRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin'
    | '/alarms'
    | '/dashboards'
    | '/reports'
    | '/wizards'
    | '/admin/data-console'
    | '/admin/gateways'
    | '/admin/meter-types'
    | '/admin/meters'
    | '/admin/sites'
    | '/admin/tenants'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/alarms'
    | '/dashboards'
    | '/reports'
    | '/wizards'
    | '/'
    | '/admin/data-console'
    | '/admin/gateways'
    | '/admin/meter-types'
    | '/admin/meters'
    | '/admin/sites'
    | '/admin/tenants'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/admin'
    | '/_authenticated/alarms'
    | '/_authenticated/dashboards'
    | '/_authenticated/reports'
    | '/_authenticated/wizards'
    | '/_authenticated/'
    | '/_authenticated/admin/data-console'
    | '/_authenticated/admin/gateways'
    | '/_authenticated/admin/meter-types'
    | '/_authenticated/admin/meters'
    | '/_authenticated/admin/sites'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wizards': {
      id: '/_authenticated/wizards'
      path: '/wizards'
      fullPath: '/wizards'
      preLoaderRoute: typeof AuthenticatedWizardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards': {
      id: '/_authenticated/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AuthenticatedDashboardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alarms': {
      id: '/_authenticated/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AuthenticatedAlarmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sites': {
      id: '/_authenticated/admin/sites'
      path: '/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AuthenticatedAdminSitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/meters': {
      id: '/_authenticated/admin/meters'
      path: '/meters'
      fullPath: '/admin/meters'
      preLoaderRoute: typeof AuthenticatedAdminMetersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/meter-types': {
      id: '/_authenticated/admin/meter-types'
      path: '/meter-types'
      fullPath: '/admin/meter-types'
      preLoaderRoute: typeof AuthenticatedAdminMeterTypesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gateways': {
      id: '/_authenticated/admin/gateways'
      path: '/gateways'
      fullPath: '/admin/gateways'
      preLoaderRoute: typeof AuthenticatedAdminGatewaysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/data-console': {
      id: '/_authenticated/admin/data-console'
      path: '/data-console'
      fullPath: '/admin/data-console'
      preLoaderRoute: typeof AuthenticatedAdminDataConsoleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDataConsoleRoute: typeof AuthenticatedAdminDataConsoleRoute
  AuthenticatedAdminGatewaysRoute: typeof AuthenticatedAdminGatewaysRoute
  AuthenticatedAdminMeterTypesRoute: typeof AuthenticatedAdminMeterTypesRoute
  AuthenticatedAdminMetersRoute: typeof AuthenticatedAdminMetersRoute
  AuthenticatedAdminSitesRoute: typeof AuthenticatedAdminSitesRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDataConsoleRoute: AuthenticatedAdminDataConsoleRoute,
  AuthenticatedAdminGatewaysRoute: AuthenticatedAdminGatewaysRoute,
  AuthenticatedAdminMeterTypesRoute: AuthenticatedAdminMeterTypesRoute,
  AuthenticatedAdminMetersRoute: AuthenticatedAdminMetersRoute,
  AuthenticatedAdminSitesRoute: AuthenticatedAdminSitesRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAlarmsRoute: typeof AuthenticatedAlarmsRoute
  AuthenticatedDashboardsRoute: typeof AuthenticatedDashboardsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedWizardsRoute: typeof AuthenticatedWizardsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAlarmsRoute: AuthenticatedAlarmsRoute,
  AuthenticatedDashboardsRoute: AuthenticatedDashboardsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedWizardsRoute: AuthenticatedWizardsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
